version: '3'
services:
  main:
    build: main
    environment:
      PORT: 9090
    ports:
      # map host's 8100 port to container's 9090 port
      - "8100:9090"
  worker:
    depends_on:
      - main
    build: worker
    environment:
      MAIN_HOST: main
      MAIN_PORT: 9090
